/*
 * ExplorerButtonPanel.java
 *
 * Created on August 24, 2006, 7:35 PM
 */

package com.floreantpos.bo.ui.explorer;

import java.awt.Color;
import java.awt.Font;

import javax.swing.JButton;

import org.apache.commons.lang.StringUtils;

import com.floreantpos.POSConstants;
import com.floreantpos.swing.TransparentPanel;

/**
 *
 * @author  rajib
 */
public class ExplorerButtonPanel extends TransparentPanel {

	private JButton editButton, addButton, deleteButton,fitButton,copyButton,extraButton,printButton,duplicateButton;

	/** Creates new form ExplorerButtonPanel */
	public ExplorerButtonPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
	private void initComponents() {

		//TransparentPanel panel = new TransparentPanel();
		editButton = new JButton();
		editButton.setFont(new Font("Times New Roman", Font.BOLD,13));
		editButton.setBackground(new Color(102,255,102));
		addButton = new JButton();
		addButton.setFont(new Font("Times New Roman", Font.BOLD,13));
		addButton.setBackground(new Color(102,255,102));
		deleteButton =new JButton();
		deleteButton.setFont(new Font("Times New Roman", Font.BOLD,13));
		deleteButton.setBackground(new Color(255,153,153));
		fitButton =new JButton();
		fitButton.setFont(new Font("Times New Roman", Font.BOLD,13));
		fitButton.setBackground(new Color(102,178,255));
		copyButton = new JButton();
		copyButton.setBackground(new Color(102,178,255));
		copyButton.setFont(new Font("Times New Roman", Font.BOLD,13));
		extraButton =new JButton();
		extraButton.setBackground(new Color(102,178,255));
		extraButton.setFont(new Font("Times New Roman", Font.BOLD,13));
		duplicateButton =new JButton();
		duplicateButton.setBackground(new Color(102,178,255));
		duplicateButton.setFont(new Font("Times New Roman", Font.BOLD,13));
		printButton =new JButton();
		printButton.setFont(new Font("Times New Roman", Font.BOLD,13));
		printButton.setText("DRUCK");		
		if(StringUtils.isNotEmpty(POSConstants.PRINT))
			deleteButton.setText(POSConstants.PRINT);
		
		printButton.setBackground(new Color(102,255,102));
		extraButton.setText("EXTRAS");
		editButton.setText(com.floreantpos.POSConstants.EDIT);
		addButton.setText(com.floreantpos.POSConstants.ADD);
		deleteButton.setText("LOESCHEN");
		if(StringUtils.isNotEmpty(POSConstants.DELETE))
			deleteButton.setText(POSConstants.DELETE);
		
		fitButton.setText("FIT");
		copyButton.setText("KOPIEREN");
		if(StringUtils.isNotEmpty(POSConstants.KOPIEREN))
			copyButton.setText(POSConstants.KOPIEREN);
		
		duplicateButton.setText("DUPLIKAT");		
		if(StringUtils.isNotEmpty(POSConstants.DUPLIKAT))
			duplicateButton.setText(POSConstants.DUPLIKAT);
		
	}

	public JButton getAddButton() {
		return addButton;
	}

	public JButton getDeleteButton() {
		return deleteButton;
	}
	
	public JButton getFitButton() {
		return fitButton;
	}
	public JButton getEditButton() {
		return editButton;
	}
	public JButton getCopyButton() {
		return copyButton;
	}
	public JButton getExtraButton() {
		return extraButton;
	}
	public JButton getPrintButton() {
		return printButton;
	}
	public JButton getDuplicateButton() {
		return duplicateButton;
	}
	// </editor-fold>    
	// Variables declaration - do not modify                     
	// End of variables declaration                   
}

