package com.floreantpos;
public class POSConstants {
	public static final String COLON = ":"; //$NON-NLS-1$	
	public static final String EDIT_TAX_RATE = Messages.getString("PosMessage.0"); //$NON-NLS-1$
	public static final String ENTER_PAYOUT_NOTE = Messages.getString("PosMessage.1"); //$NON-NLS-1$
	public static final String LOADING = Messages.getString("PosMessage.2"); //$NON-NLS-1$
	public static final String OUT_OF_MEMORY = Messages.getString("PosMessage.3"); //$NON-NLS-1$
	public static final String CREATE_TIME = Messages.getString("PosMessage.4"); //$NON-NLS-1$
	public static final String ERROR_SAVING_SHIFT_STATE = Messages.getString("PosMessage.5"); //$NON-NLS-1$
	public static final String CAPACITY = Messages.getString("PosMessage.6"); //$NON-NLS-1$
	public static final String SELECT_COUPON_TO_EDIT = Messages.getString("PosMessage.7"); //$NON-NLS-1$
	public static final String NEVER_EXPIRE = Messages.getString("PosMessage.8"); //$NON-NLS-1$
	public static final String OPEN_TICKET_SUMMARY = Messages.getString("PosMessage.9"); //$NON-NLS-1$
	public static final String DISCOUNT = Messages.getString("PosMessage.10"); //$NON-NLS-1$
	public static final String ADD_SHIFT = Messages.getString("PosMessage.11"); //$NON-NLS-1$
	public static final String AVERAGE_GUEST = "AvgGst"; //$NON-NLS-1$
	public static final String SALES_SUMMARY_REPORT = Messages.getString("PosMessage.13"); //$NON-NLS-1$
	public static final String USER_TYPES = Messages.getString("PosMessage.14"); //$NON-NLS-1$
	public static final String SERVER_NAME = Messages.getString("PosMessage.15"); //$NON-NLS-1$
	public static final String REMOVE = Messages.getString("PosMessage.16"); //$NON-NLS-1$
	public static final String DISCOUNT_COUPON_LIMIT_ = Messages.getString("PosMessage.17"); //$NON-NLS-1$
	public static final String BACK_OFFICE = Messages.getString("PosMessage.18"); //$NON-NLS-1$
	public static final String EDIT_MODIFIER_GROUP = Messages.getString("PosMessage.19"); //$NON-NLS-1$
	public static final String COUPON_TYPE = Messages.getString("PosMessage.20"); //$NON-NLS-1$
	public static final String PRINT_RECEIPT = Messages.getString("PosMessage.21"); //$NON-NLS-1$
	public static final String SERVER_PRODUCTIVITY_REPORT = Messages.getString("PosMessage.22"); //$NON-NLS-1$
	public static final String PAYROLL_REPORT = Messages.getString("PosMessage.23"); //$NON-NLS-1$
	public static final String CASHDRAWER = Messages.getString("PosMessage.24"); //$NON-NLS-1$
	public static final String SALES_ANALYSIS = Messages.getString("PosMessage.25"); //$NON-NLS-1$
	public static final String TYPE = Messages.getString("PosMessage.26"); //$NON-NLS-1$
	public static final String MODIFIER_GROUP_EXPLORER = Messages.getString("PosMessage.27"); //$NON-NLS-1$
	public static final String DRAWER_PULL = Messages.getString("PosMessage.28"); //$NON-NLS-1$
	public static final String CLEAR = Messages.getString("PosMessage.29"); //$NON-NLS-1$
	public static final String NO_SHIFT_CONFIGURED = Messages.getString("PosMessage.30"); //$NON-NLS-1$
	public static final String SHIFTS = Messages.getString("PosMessage.31"); //$NON-NLS-1$
	public static final String CONFIRM_SET_TAX_EXEMPT = Messages.getString("PosMessage.32"); //$NON-NLS-1$
	public static final String ITEMS_WASTED = Messages.getString("PosMessage.33"); //$NON-NLS-1$
	public static final String SAVE_ERROR = Messages.getString("PosMessage.34"); //$NON-NLS-1$
	public static final String SALE_BEFORE_DRAWER_RESET = Messages.getString("PosMessage.35"); //$NON-NLS-1$
	public static final String START_TIME = Messages.getString("PosMessage.36"); //$NON-NLS-1$
	public static final String CREATED = Messages.getString("PosMessage.37"); //$NON-NLS-1$
	public static final String AMOUNT = Messages.getString("PosMessage.38"); //$NON-NLS-1$
	public static final String PAY_OUT_REASON = Messages.getString("PosMessage.39"); //$NON-NLS-1$
	public static final String SALES = "Sales"; //$NON-NLS-1$
	public static final String LAND_MARK = Messages.getString("PosMessage.400"); //$NON-NLS-1$
	public static final String BELL_NAME = Messages.getString("PosMessage.401"); //$NON-NLS-1$
	public static final String SPLIT_TICKET = Messages.getString("PosMessage.41"); //$NON-NLS-1$
	public static final String SELECT_PRINTER = Messages.getString("PosMessage.42"); //$NON-NLS-1$
	public static final String SELECT_PAYMENT_TYPE = Messages.getString("PosMessage.43"); //$NON-NLS-1$
	public static final String BALANCE_DUE = Messages.getString("PosMessage.44"); //$NON-NLS-1$
	public static final String NEW_MODIFIER_GROUP = Messages.getString("PosMessage.45"); //$NON-NLS-1$
	public static final String ADMINISTRATOR = Messages.getString("PosMessage.46"); //$NON-NLS-1$
	public static final String TABLE_OCCUPIED = Messages.getString("PosMessage.47"); //$NON-NLS-1$
	public static final String SALES_BALANCE_REPORT = Messages.getString("PosMessage.48"); //$NON-NLS-1$
	public static final String MAX_QUANTITY = Messages.getString("PosMessage.49"); //$NON-NLS-1$
	public static final String REPORTS = Messages.getString("PosMessage.50"); //$NON-NLS-1$
	public static final String SETTLE = Messages.getString("PosMessage.51"); //$NON-NLS-1$
	public static final String GENERATE_REPORT = Messages.getString("PosMessage.52"); //$NON-NLS-1$
	public static final String CATEGORY_EXPLORER = Messages.getString("PosMessage.53"); //$NON-NLS-1$
	public static final String PAY_NOW = Messages.getString("PosMessage.54"); //$NON-NLS-1$
	public static final String LONG_INSTRUCTION_ERROR = Messages.getString("PosMessage.55"); //$NON-NLS-1$
	public static final String SALES_SUMMARY_KEY_STATISTICS_REPORT = Messages.getString("PosMessage.56"); //$NON-NLS-1$
	public static final String VIEW_DISCOUNTS = Messages.getString("PosMessage.57"); //$NON-NLS-1$
	public static final String GROUPS = Messages.getString("PosMessage.58"); //$NON-NLS-1$
	public static final String TEL = Messages.getString("PosMessage.59"); //$NON-NLS-1$
	public static final String SERVER = Messages.getString("PosMessage.60"); //$NON-NLS-1$
	public static final String CUSTOMER = Messages.getString("PosMessage.61"); //$NON-NLS-1$
	public static final String GENERAL = Messages.getString("PosMessage.62"); //$NON-NLS-1$
	public static final String GROUP = Messages.getString("PosMessage.63"); //$NON-NLS-1$
	public static final String RATE = Messages.getString("PosMessage.64"); //$NON-NLS-1$
	public static final String ORDER_INFO = Messages.getString("PosMessage.65"); //$NON-NLS-1$
	public static final String CANNOT_LOAD_VOID_REASONS = Messages.getString("PosMessage.66"); //$NON-NLS-1$
	public static final String DELETE_SHIFT = Messages.getString("PosMessage.67"); //$NON-NLS-1$
	public static final String PRINTER_TYPE = Messages.getString("PosMessage.68"); //$NON-NLS-1$
	public static final String USER_TYPE = Messages.getString("PosMessage.69"); //$NON-NLS-1$
	public static final String USER = Messages.getString("PosMessage.70"); //$NON-NLS-1$
	public static final String NUMBER_OF_TABLES_IS_NOT_VALID = Messages.getString("PosMessage.71"); //$NON-NLS-1$
	public static final String ENTER_ACTUAL_AMOUNT = Messages.getString("PosMessage.72"); //$NON-NLS-1$
	public static final String ENTER_YOUR_USER_ID = Messages.getString("PosMessage.73"); //$NON-NLS-1$
	public static final String DEBIT_CARD_TRANSACTION = Messages.getString("PosMessage.74"); //$NON-NLS-1$
	public static final String MENU_MODIFIERS = Messages.getString("PosMessage.75"); //$NON-NLS-1$
	public static final String CLOSED = Messages.getString("PosMessage.76"); //$NON-NLS-1$
	public static final String SHUTDOWN = Messages.getString("PosMessage.77"); //$NON-NLS-1$
	public static final String LOGIN = Messages.getString("PosMessage.78"); //$NON-NLS-1$
	public static final String TERMINAL_SETUP = Messages.getString("PosMessage.TERMINAL_SETUP"); //$NON-NLS-1$
	public static final String GO = Messages.getString("PosMessage.79"); //$NON-NLS-1$
	public static final String RECEIPT_PRINTER = Messages.getString("PosMessage.80"); //$NON-NLS-1$
	public static final String TYPE_NAME_CANNOT_BE_EMPTY = Messages.getString("PosMessage.81"); //$NON-NLS-1$
	public static final String USER_NAME = Messages.getString("PosMessage.82"); //$NON-NLS-1$
	public static final String USER_NOT_FOUND = Messages.getString("PosMessage.83"); //$NON-NLS-1$
	public static final String EDIT = Messages.getString("PosMessage.84"); //$NON-NLS-1$
	public static final String END_DATE = Messages.getString("PosMessage.85"); //$NON-NLS-1$
	public static final String RESTAURANT_NAME = Messages.getString("PosMessage.86"); //$NON-NLS-1$
	public static final String TOTAL = Messages.getString("PosMessage.87"); //$NON-NLS-1$
	public static final String TOTAL_COUNT = Messages.getString("PosMessage.350"); //$NON-NLS-1$
	public static final String PROVIDE_CORRECT_FORMAT = Messages.getString("PosMessage.351"); //$NON-NLS-1$
	public static final String REQUIRED_MODIFIERS_NOT_ADDED = Messages.getString("PosMessage.88"); //$NON-NLS-1$
	public static final String DISABLED = Messages.getString("PosMessage.89"); //$NON-NLS-1$
	public static final String INSTRUCTION_CANNOT_BE_EMPTY = Messages.getString("PosMessage.90"); //$NON-NLS-1$
	public static final String TABLE = Messages.getString("PosMessage.91"); //$NON-NLS-1$
	public static final String NAME_REQUIRED = Messages.getString("PosMessage.92"); //$NON-NLS-1$
	public static final String THERE_WAS_AN_ERROR_WHILE_PRINTING_TO_KITCHEN = Messages.getString("PosMessage.93"); //$NON-NLS-1$
	public static final String TIME = Messages.getString("PosMessage.94"); //$NON-NLS-1$
	public static final String VOID_REASON = Messages.getString("PosMessage.95"); //$NON-NLS-1$
	public static final String SELECT_USER = Messages.getString("PosMessage.96"); //$NON-NLS-1$
	public static final String OPEN_TICKET_SUMMARY_REPORT = Messages.getString("PosMessage.97"); //$NON-NLS-1$
	public static final String CONFIGURE = Messages.getString("PosMessage.98"); //$NON-NLS-1$
	public static final String TICKET_DETAIL = Messages.getString("PosMessage.99"); //$NON-NLS-1$
	public static final String ERROR_MESSAGE = Messages.getString("PosMessage.100"); //$NON-NLS-1$   
	public static final String CONFIRM_SHUTDOWN = Messages.getString("PosMessage.101"); //$NON-NLS-1$	
	public static final String NEW_TAX_RATE = Messages.getString("PosMessage.103"); //$NON-NLS-1$
	public static final String HOURLY_LABOR_REPORT = Messages.getString("PosMessage.104"); //$NON-NLS-1$	
	public static final String GIFT_CERTIFICATE = Messages.getString("PosMessage.106"); //$NON-NLS-1$
	public static final String AMOUNT_PAID_OUT = Messages.getString("PosMessage.107"); //$NON-NLS-1$
	public static final String AM = Messages.getString("PosMessage.108"); //$NON-NLS-1$
	public static final String ADD = Messages.getString("PosMessage.109"); //$NON-NLS-1$
	public static final String DATE = Messages.getString("PosMessage.110"); //$NON-NLS-1$
	public static final String ENTER_AMOUNT = Messages.getString("PosMessage.111"); //$NON-NLS-1$
	public static final String DETAILS = Messages.getString("PosMessage.112"); //$NON-NLS-1$
	public static final String ITEM = Messages.getString("PosMessage.113"); //$NON-NLS-1$
	public static final String TO = Messages.getString("PosMessage.114"); //$NON-NLS-1$
	public static final String MENU_USAGE_REPORT = Messages.getString("PosMessage.115"); //$NON-NLS-1$
	public static final String COUPON_DISCOUNT_EXPLORER = Messages.getString("PosMessage.116"); //$NON-NLS-1$
	public static final String NEW_SHIFT = Messages.getString("PosMessage.117"); //$NON-NLS-1$
	public static final String DISCOUNT_RATE = Messages.getString("PosMessage.118"); //$NON-NLS-1$
	public static final String CLEAR_ALL = Messages.getString("PosMessage.119"); //$NON-NLS-1$
	public static final String SHIFT_END_TIME_MUST_BE_GREATER_THAN_SHIFT_START_TIME = Messages.getString("PosMessage.120"); //$NON-NLS-1$
	public static final String VISIBLE = Messages.getString("PosMessage.121"); //$NON-NLS-1$
	public static final String CREATED_BY = Messages.getString("PosMessage.122"); //$NON-NLS-1$
	public static final String ITEMS = Messages.getString("PosMessage.123"); //$NON-NLS-1$
	public static final String MANAGER = Messages.getString("PosMessage.124"); //$NON-NLS-1$
	public static final String MODIFIER_EXPLORER = Messages.getString("PosMessage.125"); //$NON-NLS-1$
	public static final String USERS = Messages.getString("PosMessage.126"); //$NON-NLS-1$
	public static final String MIN = Messages.getString("PosMessage.127"); //$NON-NLS-1$
	public static final String GROUP_NAME = Messages.getString("PosMessage.128"); //$NON-NLS-1$
	public static final String SALES_REPORT = Messages.getString("PosMessage.129"); //$NON-NLS-1$
	public static final String HOUR = Messages.getString("PosMessage.130"); //$NON-NLS-1$
	public static final String SERVER_ID = Messages.getString("PosMessage.131"); //$NON-NLS-1$
	public static final String WRONG_PASSWORD = Messages.getString("PosMessage.132"); //$NON-NLS-1$
	public static final String ADDRESS_LINE1 = Messages.getString("PosMessage.133"); //$NON-NLS-1$
	public static final String ADDRESS_LINE2 = Messages.getString("PosMessage.134"); //$NON-NLS-1$
	public static final String PRINT = Messages.getString("PosMessage.135"); //$NON-NLS-1$
	public static final String TRANSACTION_COMPLETED = Messages.getString("PosMessage.136"); //$NON-NLS-1$
	public static final String NOTES = Messages.getString("PosMessage.137"); //$NON-NLS-1$
	public static final String MENU_CATEGORY = Messages.getString("PosMessage.138"); //$NON-NLS-1$
	public static final String ORIGINAL_TICKET_ID = Messages.getString("PosMessage.139"); //$NON-NLS-1$
	public static final String MODIFIER_GROUP_REQUIRED = Messages.getString("PosMessage.140"); //$NON-NLS-1$
	public static final String USER_ID = Messages.getString("PosMessage.141"); //$NON-NLS-1$
	public static final String CREDIT_CARD_REPORT = Messages.getString("PosMessage.142"); //$NON-NLS-1$
	public static final String PERMISSIONS = Messages.getString("PosMessage.143"); //$NON-NLS-1$
	public static final String CLOSE = Messages.getString("PosMessage.144"); //$NON-NLS-1$
	public static final String SHIFT_NAME_ALREADY_EXISTS = Messages.getString("PosMessage.145"); //$NON-NLS-1$
	public static final String DRAWER_PULL_AMOUNT = Messages.getString("PosMessage.146"); //$NON-NLS-1$
	public static final String TAX_EXEMPT = Messages.getString("PosMessage.147"); //$NON-NLS-1$
	public static final String CREDIT_CARD_TRANSACTION = Messages.getString("PosMessage.148"); //$NON-NLS-1$
	public static final String MENU_CATEGORIES = Messages.getString("PosMessage.149"); //$NON-NLS-1$
	public static final String ENTER_ID_FOR_TERMINAL = Messages.getString("PosMessage.150"); //$NON-NLS-1$
	public static final String GROUP_EXPLORER = Messages.getString("PosMessage.151"); //$NON-NLS-1$
	public static final String PRINT_TO_KITCHEN_WHEN_TICKET_PAID = Messages.getString("PosMessage.152"); //$NON-NLS-1$
	public static final String SUBTOTAL = Messages.getString("PosMessage.153"); //$NON-NLS-1$
	public static final String NEW_MENU_ITEM = Messages.getString("PosMessage.154"); //$NON-NLS-1$
	public static final String SHIFT_NAME = Messages.getString("PosMessage.155"); //$NON-NLS-1$
	public static final String ACTUAL_AMOUNT = Messages.getString("PosMessage.156"); //$NON-NLS-1$
	public static final String BANK_CHECK = Messages.getString("PosMessage.157"); //$NON-NLS-1$
	public static final String TITLE = Messages.getString("PosMessage.158"); //$NON-NLS-1$
	public static final String MANAGER_FUNCTION = Messages.getString("PosMessage.159"); //$NON-NLS-1$
	public static final String SYSTEM_TOTAL = Messages.getString("PosMessage.160"); //$NON-NLS-1$
	public static final String SALES_EXCEPTION_REPORT = Messages.getString("PosMessage.161"); //$NON-NLS-1$
	public static final String CONFIRM_PARTIAL_PAYMENT = Messages.getString("PosMessage.162"); //$NON-NLS-1$
	public static final String SELECT_TICKET = Messages.getString("PosMessage.163"); //$NON-NLS-1$
	public static final String NEW = Messages.getString("PosMessage.164"); //$NON-NLS-1$
	public static final String TELEPHONE = Messages.getString("PosMessage.165"); //$NON-NLS-1$
	public static final String DRAWER_BLEED = Messages.getString("PosMessage.166"); //$NON-NLS-1$
	public static final String FIRST_NAME = Messages.getString("PosMessage.167"); //$NON-NLS-1$
	public static final String EDIT_MENU_ITEM = Messages.getString("PosMessage.168"); //$NON-NLS-1$
	public static final String COUPON_DISCOUNT = Messages.getString("PosMessage.169"); //$NON-NLS-1$
	public static final String ADD_GRATUITY_TEXT = Messages.getString("ADD_GRATUITY_TEXT"); //$NON-NLS-1$
	public static final String PRINT_ERROR = Messages.getString("PosMessage.170"); //$NON-NLS-1$
	public static final String SALES_SUMMARY_KEY_STATISTICS = Messages.getString("PosMessage.171"); //$NON-NLS-1$
	public static final String SELECT_SHIFT = Messages.getString("PosMessage.172"); //$NON-NLS-1$
	public static final String PRINT_RECEIPT_WHEN_TICKET_SETTLED = Messages.getString("PosMessage.173"); //$NON-NLS-1$
	public static final String CANCEL = Messages.getString("PosMessage.174"); //$NON-NLS-1$
	public static final String TICKET_IS_EMPTY_ = Messages.getString("PosMessage.175"); //$NON-NLS-1$
	public static final String MENU_ITEMS = Messages.getString("PosMessage.176"); //$NON-NLS-1$
	public static final String DATE_TIME = Messages.getString("PosMessage.177"); //$NON-NLS-1$
	public static final String TAX = Messages.getString("PosMessage.178"); //$NON-NLS-1$
	public static final String NAME = Messages.getString("PosMessage.179"); //$NON-NLS-1$
	public static final String EDIT_MENU_CATEGORY = Messages.getString("PosMessage.180"); //$NON-NLS-1$
	public static final String DESCRIPTION = Messages.getString("PosMessage.181"); //$NON-NLS-1$
	public static final String INVALID_AMOUNT = Messages.getString("PosMessage.182"); //$NON-NLS-1$
	public static final String SELECT_CRIETERIA = Messages.getString("PosMessage.183"); //$NON-NLS-1$
	public static final String USER_LIST = Messages.getString("PosMessage.184"); //$NON-NLS-1$
	public static final String SELECT_DRAWER_PULL_TO_EDIT = Messages.getString("PosMessage.185"); //$NON-NLS-1$
	public static final String EXPIRY_DATE = Messages.getString("PosMessage.186"); //$NON-NLS-1$
	public static final String START_DATE = Messages.getString("PosMessage.187"); //$NON-NLS-1$
	public static final String ADMIN = Messages.getString("PosMessage.188"); //$NON-NLS-1$
	public static final String PRINT_RECEIPT_WHEN_TICKET_PAID = Messages.getString("PosMessage.189"); //$NON-NLS-1$
	public static final String PRINT_TO_KITCHEN_WHEN_TICKET_SETTLED = Messages.getString("PosMessage.190"); //$NON-NLS-1$
	public static final String ENTER_YOUR_PASSWORD = Messages.getString("PosMessage.191"); //$NON-NLS-1$
	public static final String VOID = Messages.getString("PosMessage.192"); //$NON-NLS-1$
	public static final String TAX_RATE = Messages.getString("PosMessage.193"); //$NON-NLS-1$
	public static final String SELECT_COUPON_TO_DELETE = Messages.getString("PosMessage.194"); //$NON-NLS-1$
	public static final String CONFIGURE_DATABASE = Messages.getString("PosMessage.195"); //$NON-NLS-1$
	public static final String EXPLORERS = Messages.getString("PosMessage.196"); //$NON-NLS-1$
	public static final String TOTAL_GRATUITY = Messages.getString("PosMessage.197"); //$NON-NLS-1$
	public static final String PRICE = Messages.getString("PosMessage.198"); //$NON-NLS-1$
	public static final String SRV_ = Messages.getString("PosMessage.199"); //$NON-NLS-1$
	public static final String MISC_ITEM = Messages.getString("PosMessage.200"); //$NON-NLS-1$
	public static final String TABLE_NUMBER = Messages.getString("PosMessage.201"); //$NON-NLS-1$
	public static final String ACTIVE_TICKETS_BEFORE_DRAWER_RESET = Messages.getString("PosMessage.202"); //$NON-NLS-1$
	public static final String DUE = Messages.getString("PosMessage.203"); //$NON-NLS-1$
	
	public static final String MODIFIER_GROUPS = Messages.getString("PosMessage.205"); //$NON-NLS-1$
	public static final String CATEGORY = Messages.getString("PosMessage.206"); //$NON-NLS-1$
	public static final String OK = Messages.getString("PosMessage.207"); //$NON-NLS-1$
	public static final String VOID_TICKET = Messages.getString("PosMessage.208"); //$NON-NLS-1$
	public static final String TICKET = Messages.getString("PosMessage.209"); //$NON-NLS-1$
	public static final String DELETE = Messages.getString("PosMessage.210"); //$NON-NLS-1$
	public static final String QTY = Messages.getString("PosMessage.211"); //$NON-NLS-1$
	public static final String CONFIRM_DELETE = Messages.getString("PosMessage.212"); //$NON-NLS-1$
	public static final String GUEST = "Pers. Anzahl:"; //$NON-NLS-1$
	public static final String EMPTY_PASSWORD = Messages.getString("PosMessage.214"); //$NON-NLS-1$
	public static final String TABLES = Messages.getString("PosMessage.215"); //$NON-NLS-1$
	public static final String SWITCHBOARD = Messages.getString("PosMessage.216"); //$NON-NLS-1$
	public static final String FOOD_GROUP = Messages.getString("PosMessage.217"); //$NON-NLS-1$
	public static final String NUMBER_OF_GUESTS = Messages.getString("PosMessage.218"); //$NON-NLS-1$
	public static final String PERFORMING_AUTO_DRAWER_PULL = Messages.getString("PosMessage.219"); //$NON-NLS-1$
	public static final String ENTER_INSTRUCTION_DESCRIPTION = Messages.getString("PosMessage.220"); //$NON-NLS-1$
	public static final String RESTAURANT_NAME_ = Messages.getString("PosMessage.221"); //$NON-NLS-1$
	public static final String PM = Messages.getString("PosMessage.222"); //$NON-NLS-1$
	public static final String DRAWER_PULL_REPORTS = Messages.getString("PosMessage.223"); //$NON-NLS-1$
	public static final String FINISH = Messages.getString("PosMessage.224"); //$NON-NLS-1$
	public static final String CHECK = "Check"; //$NON-NLS-1$
	public static final String SETTLE_TIME = Messages.getString("PosMessage.226"); //$NON-NLS-1$
	public static final String FROM = Messages.getString("PosMessage.227"); //$NON-NLS-1$
	public static final String MISC = Messages.getString("PosMessage.228"); //$NON-NLS-1$
	public static final String COUPON_VALUE = Messages.getString("PosMessage.229"); //$NON-NLS-1$
	public static final String OTHERS = Messages.getString("PosMessage.231"); //$NON-NLS-1$
	public static final String CASHIER = Messages.getString("PosMessage.232"); //$NON-NLS-1$
	public static final String DOLLAR = Messages.getString("PosMessage.233"); //$NON-NLS-1$
	public static final String MIN_QUANTITY = Messages.getString("PosMessage.234"); //$NON-NLS-1$
	public static final String CURRENCY_NAME_ = Messages.getString("PosMessage.235"); //$NON-NLS-1$
	public static final String PREVIOUS_SALE_AFTER_DRAWER_RESET_ = Messages.getString("PosMessage.236"); //$NON-NLS-1$
	public static final String SALES_DETAILED_REPORT = Messages.getString("PosMessage.237"); //$NON-NLS-1$
	public static final String YOU_CANNOT_PARTIALLY_PAY_MULTIPLE_TICKETS_ = Messages.getString("PosMessage.238"); //$NON-NLS-1$
	public static final String ADD_NEW_MODIFIER_GROUP_IN_MENU_ITEM_ = Messages.getString("PosMessage.239"); //$NON-NLS-1$
	public static final String PRINTER_NAME_ = Messages.getString("PosMessage.240"); //$NON-NLS-1$
	public static final String UPRICE = Messages.getString("PosMessage.241"); //$NON-NLS-1$
	public static final String UPDATING_SYSTEM_PLEASE_WAIT_ = Messages.getString("PosMessage.242"); //$NON-NLS-1$
	public static final String AVGCHK = "AvgChk"; //$NON-NLS-1$
	public static final String TO_ = Messages.getString("PosMessage.244"); //$NON-NLS-1$
	public static final String JOURNAL_REPORT = Messages.getString("PosMessage.245"); //$NON-NLS-1$
	public static final String USER_TYPE_EXPLORER = Messages.getString("PosMessage.246"); //$NON-NLS-1$
	public static final String CONFIGURATION = Messages.getString("PosMessage.247"); //$NON-NLS-1$
	public static final String GUEST_NUMBER_CANNOT_BE_0 = Messages.getString("PosMessage.248"); //$NON-NLS-1$
	public static final String SURE_EXIT = Messages.getString("PosMessage.249"); //$NON-NLS-1$
	public static final String ID = Messages.getString("PosMessage.250"); //$NON-NLS-1$
	public static final String SELECT_COOKING_INSTRUCTION = Messages.getString("PosMessage.251"); //$NON-NLS-1$
	public static final String CURRENCY_SYMBOL_ = Messages.getString("PosMessage.252"); //$NON-NLS-1$
	public static final String EDIT_ACTUAL_AMOUNT = Messages.getString("PosMessage.253"); //$NON-NLS-1$
	public static final String MENU_MODIFIER_GROUPS = Messages.getString("PosMessage.254"); //$NON-NLS-1$
	public static final String MODIFIERS = Messages.getString("PosMessage.255"); //$NON-NLS-1$
	public static final String TICKET_ID = Messages.getString("PosMessage.256"); //$NON-NLS-1$
	public static final String PRINT_TO_KITCHEN = Messages.getString("PosMessage.257"); //$NON-NLS-1$
	public static final String PAID = Messages.getString("PosMessage.258"); //$NON-NLS-1$
	public static final String CAPACITY_IS_NOT_VALID_ = Messages.getString("PosMessage.259"); //$NON-NLS-1$
	public static final String BEVERAGE = Messages.getString("PosMessage.260"); //$NON-NLS-1$
	public static final String ITEM_EXPLORER = Messages.getString("PosMessage.261"); //$NON-NLS-1$
	public static final String COPY = Messages.getString("PosMessage.262"); //$NON-NLS-1$
	public static final String ALL = Messages.getString("PosMessage.263"); //$NON-NLS-1$
	public static final String PAY_TIPS = Messages.getString("PosMessage.264"); //$NON-NLS-1$
	public static final String COOKING_INSTRUCTIONS = Messages.getString("PosMessage.265"); //$NON-NLS-1$
	public static final String LAST_NAME = Messages.getString("PosMessage.266"); //$NON-NLS-1$
	public static final String TYPE_NAME = Messages.getString("PosMessage.267"); //$NON-NLS-1$
	public static final String OFFICIAL_RECEIPT = Messages.getString("PosMessage.403"); //$NON-NLS-1$
	public static final String CREDIT = Messages.getString("PosMessage.404"); //$NON-NLS-1$
	public static final String OFFER = Messages.getString("PosMessage.410"); //$NON-NLS-1$
	public static final String CASH_TRANSACTION = Messages.getString("PosMessage.269"); //$NON-NLS-1$
	public static final String ENTER_VOID_REASON = Messages.getString("PosMessage.270"); //$NON-NLS-1$
	public static final String DRAWER_PULL_ = Messages.getString("PosMessage.271"); //$NON-NLS-1$
	public static final String MENU_GROUPS = Messages.getString("PosMessage.272"); //$NON-NLS-1$
	public static final String ITEM_NAME = Messages.getString("PosMessage.273"); //$NON-NLS-1$
	public static final String ACTIVE_TICKETS = Messages.getString("PosMessage.274"); //$NON-NLS-1$
	public static final String TBL_ = Messages.getString("PosMessage.275"); //$NON-NLS-1$
	public static final String PAY = Messages.getString("PosMessage.276"); //$NON-NLS-1$
	public static final String OPEN_TICKETS = Messages.getString("PosMessage.277"); //$NON-NLS-1$
	public static final String MODIFIER_GROUP = Messages.getString("PosMessage.278"); //$NON-NLS-1$
	public static final String MDS_POS = Messages.getString("PosMessage.279"); //$NON-NLS-1$
	public static final String PRICE_IS_NOT_VALID_ = Messages.getString("PosMessage.280"); //$NON-NLS-1$
	public static final String ENTER = "Enter"; //$NON-NLS-1$
	public static final String ADDRESS_LINE3 = Messages.getString("PosMessage.282"); //$NON-NLS-1$
	public static final String NUMBER_OF_PRINT_SERVICES_ = Messages.getString("PosMessage.283"); //$NON-NLS-1$
	public static final String FROM_DATE_CANNOT_BE_GREATER_THAN_TO_DATE_ = Messages.getString("PosMessage.284"); //$NON-NLS-1$
	public static final String TABLE_NUMBER_CANNOT_BE_0 = Messages.getString("PosMessage.285"); //$NON-NLS-1$
	public static final String TERMINAL_LABEL = Messages.getString("TERMINAL_LABEL"); //$NON-NLS-1$
	public static final String CAPACITY_ = Messages.getString("PosMessage.287"); //$NON-NLS-1$
	public static final String UNNABLE_TO_SAVE_ = Messages.getString("PosMessage.288"); //$NON-NLS-1$
	public static final String SELECT_ITEM_TO_DELETE = Messages.getString("PosMessage.289"); //$NON-NLS-1$
	public static final String GRATUITY_ADMINISTRATION = Messages.getString("PosMessage.290"); //$NON-NLS-1$
	public static final String USER_ID_NOT_VALID = Messages.getString("PosMessage.291"); //$NON-NLS-1$
	public static final String SAVE = Messages.getString("PosMessage.292"); //$NON-NLS-1$
	public static final String NUMBER_OF_SPLITS = Messages.getString("PosMessage.293"); //$NON-NLS-1$
	public static final String EDIT_MODIFIER_GROUP_IN_MENU_ITEM_ = Messages.getString("PosMessage.294"); //$NON-NLS-1$
	public static final String SERVER_TIPS = Messages.getString("PosMessage.295"); //$NON-NLS-1$
	public static final String OPEN = Messages.getString("PosMessage.296"); //$NON-NLS-1$
	public static final String CONFIRM = Messages.getString("PosMessage.297"); //$NON-NLS-1$
	public static final String DAYPART = "DayPart"; //$NON-NLS-1$
	public static final String BY_RANGE_ACTUAL = Messages.getString("PosMessage.299"); //$NON-NLS-1$
	public static final String COUPONS_AND_DISCOUNTS = Messages.getString("PosMessage.300"); //$NON-NLS-1$
	public static final String EXTRA_PRICE = Messages.getString("PosMessage.301"); //$NON-NLS-1$
	public static final String AUTO_DRAWER_PULL_EVERY_DAY_AT_ = Messages.getString("PosMessage.302"); //$NON-NLS-1$
	public static final String SELECT_PAY_OUT_RECEPIENT = Messages.getString("PosMessage.303"); //$NON-NLS-1$
	public static final String CATEGORIES = Messages.getString("PosMessage.304"); //$NON-NLS-1$
	public static final String END_TIME = Messages.getString("PosMessage.305"); //$NON-NLS-1$
	public static final String SERVER_TIPS_REPORT = Messages.getString("PosMessage.306"); //$NON-NLS-1$
	public static final String DATABASE_CONNECTION_ERROR = Messages.getString("PosMessage.307"); //$NON-NLS-1$
	public static final String NEW_MENU_CATEGORY = Messages.getString("PosMessage.308"); //$NON-NLS-1$
	public static final String SAVE_CUSTOMER = Messages.getString("PosMessage.352"); //$NON-NLS-1$
	public static final String PERCENTAGE = Messages.getString("PosMessage.309"); //$NON-NLS-1$
	public static final String WELCOME = Messages.getString("Switchboard.0"); //$NON-NLS-1$
	public static final String OPEN_TICKETS_AND_ACTIVITY = Messages.getString("Switchboard.1"); //$NON-NLS-1$
	public static final String TICKETS = Messages.getString("Switchboard.2"); //$NON-NLS-1$
	public static final String HAVE = Messages.getString("Switchboard.3"); //$NON-NLS-1$
	public static final String YOU = Messages.getString("Switchboard.4"); //$NON-NLS-1$
	public static final String YOU_MUST_SELECT_TWO_OR_MORE_TICKET_FOR_GROUP_SETTLE = Messages.getString("Switchboard.5"); //$NON-NLS-1$
	public static final String SELECT_A_TICKET_FROM_THE_OPEN_TICKET_LIST = Messages.getString("Switchboard.6"); //$NON-NLS-1$
	public static final String ENTER_NUMBER_OF_GUEST = Messages.getString("Switchboard.7"); //$NON-NLS-1$
	public static final String EDIT_TICKET_CONFIRMATION = Messages.getString("Switchboard.8"); //$NON-NLS-1$
	public static final String ENTER_A_TABLE_NUMBER = Messages.getString("Switchboard.9"); //$NON-NLS-1$
	public static final String SELECT_ONE_TICKET_TO_EDIT = Messages.getString("Switchboard.10"); //$NON-NLS-1$
	public static final String SELECT_ONE_TICKET_TO_SPLIT = Messages.getString("Switchboard.11"); //$NON-NLS-1$
	public static final String PARTIAL_PAID_VOID_ERROR = Messages.getString("Switchboard.12"); //$NON-NLS-1$
	public static final String SELECT_ONE_TICKET_TO_VOID = Messages.getString("Switchboard.13"); //$NON-NLS-1$
	public static final String SELECT_ONE_TICKET_TO_PRINT = Messages.getString("Switchboard.14"); //$NON-NLS-1$
	public static final String SELECT_ONE_TICKET_TO_SETTLE = Messages.getString("Switchboard.15"); //$NON-NLS-1$
	public static final String CONFIRM_CLOCK_OUT = Messages.getString("Switchboard.16"); //$NON-NLS-1$
	public static final String FOUND = Messages.getString("Switchboard.17"); //$NON-NLS-1$
	public static final String NO_TICKET_WITH_ID = Messages.getString("Switchboard.18"); //$NON-NLS-1$
	public static final String TICKET_IS_NOT_CLOSED = Messages.getString("Switchboard.19"); //$NON-NLS-1$
	public static final String ENTER_TICKET_ID = Messages.getString("Switchboard.20"); //$NON-NLS-1$
	public static final String CAPITAL_CLOCK_OUT = Messages.getString("Switchboard.21"); //$NON-NLS-1$
	public static final String CAPITAL_MANAGER = Messages.getString("Switchboard.22"); //$NON-NLS-1$
	public static final String CAPITAL_BACK_OFFICE = Messages.getString("Switchboard.23"); //$NON-NLS-1$
	public static final String CAPITAL_LOGOUT = Messages.getString("Switchboard.24"); //$NON-NLS-1$
	public static final String CAPITAL_SHUTDOWN = Messages.getString("Switchboard.25"); //$NON-NLS-1$
	public static final String CAPITAL_INFO = Messages.getString("Switchboard.26"); //$NON-NLS-1$
	public static final String CAPITAL_NEW = Messages.getString("Switchboard.27"); //$NON-NLS-1$
	public static final String CAPITAL_EDIT = Messages.getString("Switchboard.28"); //$NON-NLS-1$
	public static final String CAPITAL_SPLIT = Messages.getString("Switchboard.29"); //$NON-NLS-1$
	public static final String CAPITAL_VOID = Messages.getString("Switchboard.30"); //$NON-NLS-1$
	public static final String CAPITAL_RE_OPEN = Messages.getString("Switchboard.31"); //$NON-NLS-1$
	public static final String CAPITAL_SETTLE = Messages.getString("Switchboard.32"); //$NON-NLS-1$
	public static final String CAPITAL_PRINT = Messages.getString("Switchboard.33"); //$NON-NLS-1$
	public static final String CAPITAL_TAKE_OUT = Messages.getString("Switchboard.34"); //$NON-NLS-1$
	public static final String CAPITAL_PAY_OUT = Messages.getString("Switchboard.35"); //$NON-NLS-1$
	public static final String CAPITAL_GROUP = Messages.getString("Switchboard.36"); //$NON-NLS-1$
	public static final String HOME_OPEN_TICKETS = Messages.getString("Switchboard.37"); //$NON-NLS-1$
	public static final String HOME_PAID = Messages.getString("Switchboard.38"); //$NON-NLS-1$
	public static final String ALL_ORDERS = Messages.getString("Switchboard.39"); //$NON-NLS-1$
	public static final String DAILY_REPORT = Messages.getString("Switchboard.40"); //$NON-NLS-1$
	public static final String MONTHLY_REPORT = Messages.getString("Switchboard.41"); //$NON-NLS-1$
	
	public static final String DRIVER_REPORT = Messages.getString("Switchboard.42"); //$NON-NLS-1$
	public static final String EMPLOYEE_REPORT = Messages.getString("Switchboard.43"); //$NON-NLS-1$
	public static final String BON_BESTELLUGEN = Messages.getString("Switchboard.44"); //$NON-NLS-1$
	public static final String TERMINE = Messages.getString("Switchboard.45"); //$NON-NLS-1$
	public static final String TISCHE = Messages.getString("Switchboard.46"); //$NON-NLS-1$
	
	
	public static final String INVALID_NUMBER = Messages.getString("PosMessage.310"); //$NON-NLS-1$
	public static final String CAPITAL_COOKING_INSTRUCTIONS = Messages.getString("PosMessage.311"); //$NON-NLS-1$
	public static final String CAPITAL_BACK = Messages.getString("SelectionView.0"); //$NON-NLS-1$
	public static final String CAPITAL_NEXT = Messages.getString("SelectionView.1"); //$NON-NLS-1$
	public static final String CAPITAL_PREV = Messages.getString("SelectionView.2"); //$NON-NLS-1$
	public static final String DEFAULT_TIPS_PERCENTAGE = Messages.getString("DEFAULT_TIPS_PERCENTAGE"); //$NON-NLS-1$
	public static final String TAX_EXPLORER = Messages.getString("POSConstants.TAX_EXPLORER"); //$NON-NLS-1$
	public static final String TICKET_DELIVERY_DATE = Messages.getString("POSConstants.TICKET_DELIVERY_DATE"); //$NON-NLS-1$
	public static final String TICKET_TYPE = Messages.getString("POSConstants.TICKET_TYPE"); //$NON-NLS-1$

	public static final String POS_MESSAGE_ERROR = "PosMessage.Error";
	
	public static final String CONFIG_TAB_RESTAURANT = Messages.getString("CONFIG_TAB_RESTAURANT"); //$NON-NLS-1$
	public static final String CONFIG_TAB_TAX = Messages.getString("CONFIG_TAB_TAX"); //$NON-NLS-1$
	public static final String CONFIG_TAB_PRINT = Messages.getString("CONFIG_TAB_PRINT"); //$NON-NLS-1$
	
	public static final String RECEIPT_REPORT_TERMINAL_LABEL = Messages.getString("RECEIPT_REPORT_TERMINAL_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_TICKET_NO_LABEL = Messages.getString("RECEIPT_REPORT_TICKET_NO_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_TABLE_NO_LABEL = Messages.getString("RECEIPT_REPORT_TABLE_NO_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_GUEST_NO_LABEL = Messages.getString("RECEIPT_REPORT_GUEST_NO_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_SERVER_LABEL = Messages.getString("RECEIPT_REPORT_SERVER_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_DATE_LABEL = Messages.getString("RECEIPT_REPORT_DATE_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_ITEM_LABEL = Messages.getString("RECEIPT_REPORT_ITEM_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_ITEM_ID_LABEL = Messages.getString("RECEIPT_REPORT_ITEM_ID_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_QUANTITY_LABEL = Messages.getString("RECEIPT_REPORT_QUANTITY_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_SUBTOTAL_LABEL = Messages.getString("RECEIPT_REPORT_SUBTOTAL_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_TOTAL_LABEL = Messages.getString("RECEIPT_REPORT_TOTAL_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_DISCOUNT_LABEL = Messages.getString("RECEIPT_REPORT_DISCOUNT_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_TAX_LABEL = Messages.getString("RECEIPT_REPORT_TAX_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_TAX_HOMED_DLABEL = Messages.getString("RECEIPT_REPORT_TAX_HOMED_DLABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_TAX_DINEIN_DLABEL = Messages.getString("RECEIPT_REPORT_TAX_DINEIN_DLABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_SERVICE_CHARGE_LABEL = Messages.getString("RECEIPT_REPORT_SERVICE_CHARGE_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_TIPS_LABEL = Messages.getString("RECEIPT_REPORT_TIPS_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_NETAMOUNT_LABEL = Messages.getString("RECEIPT_REPORT_NETAMOUNT_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_PAIDAMOUNT_LABEL = Messages.getString("RECEIPT_REPORT_PAIDAMOUNT_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_DUEAMOUNT_LABEL = Messages.getString("RECEIPT_REPORT_DUEAMOUNT_LABEL"); //$NON-NLS-1$
	public static final String RECEIPT_REPORT_CHANGEAMOUNT_LABEL = Messages.getString("RECEIPT_REPORT_CHANGEAMOUNT_LABEL"); //$NON-NLS-1$
	public static final String DINE_IN_OPEN = Messages.getString("DINE_IN_OPEN"); //$NON-NLS-1$
	public static final String HOME_OPEN = Messages.getString("HOME_OPEN"); //$NON-NLS-1$
	public static final String HOME_CLOSED = Messages.getString("HOME_CLOSED"); //$NON-NLS-1$
	public static final String ALL_TICKETS = Messages.getString("ALL_TICKETS"); //$NON-NLS-1$
	public static final String ENTER_ITEM_ID = Messages.getString("PosMessage.312"); //$NON-NLS-1$
	public static final String SEARCH = Messages.getString("PosMessage.313"); //$NON-NLS-1$
	public static final String PAY_LATER = Messages.getString("PosMessage.314"); //$NON-NLS-1$
	public static final String RECEIPT_NR = Messages.getString("PosMessage.315"); //$NON-NLS-1$ 
	public static final String TOTAL_AMOUNT = Messages.getString("PosMessage.316"); //$NON-NLS-1$
	public static final String NET_AMOUNT = Messages.getString("PosMessage.317"); //$NON-NLS-1$
	public static final String ASSIGN_DRIVER = Messages.getString("PosMessage.318"); //$NON-NLS-1$
	public static final String REOPEN = Messages.getString("PosMessage.319"); //$NON-NLS-1$
	public static final String CLOSE_ORDER = Messages.getString("PosMessage.320"); //$NON-NLS-1$
	public static final String DINE_IN = Messages.getString("PosMessage.321"); //$NON-NLS-1$
	public static final String HOME_DELIVERY = Messages.getString("PosMessage.322"); //$NON-NLS-1$
	public static final String HERR = Messages.getString("PosMessage.323"); //$NON-NLS-1$
	public static final String FRAU = Messages.getString("PosMessage.324"); //$NON-NLS-1$
	public static final String EXIT = Messages.getString("PosMessage.325"); //$NON-NLS-1$
	public static final String SURE_SHUTDOWN = Messages.getString("PosMessage.326"); //$NON-NLS-1$
	public static final String NEW_ORDER = Messages.getString("PosMessage.402"); //$NON-NLS-1$
	public static final String MISC_HOME_DELEVERY = Messages.getString("PosMessage.405"); //$NON-NLS-1$
	public static final String MISC_DINE_IN = Messages.getString("PosMessage.406"); //$NON-NLS-1$
	public static final String LAST_FIVE_BILL = Messages.getString("PosMessage.407"); //$NON-NLS-1$
	public static final String MORE = Messages.getString("PosMessage.408"); //$NON-NLS-1$
	public static final String CASH_PAID = Messages.getString("PosMessage.327"); //$NON-NLS-1$
	public static final String CARD_PAID = Messages.getString("PosMessage.328"); //$NON-NLS-1$
	public static final String ONLINE_PAID = Messages.getString("PosMessage.329"); //$NON-NLS-1$
	public static final String NOT_PAID = Messages.getString("PosMessage.330"); //$NON-NLS-1$
	public static final String BOTH_PAID = Messages.getString("PosMessage.331"); //$NON-NLS-1$
	public static final String BILL = Messages.getString("PosMessage.409"); //$NON-NLS-1$
	
	public static final String ARTICKEL_CANCEL = Messages.getString("PosMessage.411"); //$NON-NLS-1$
	public static final String ARTICKEL_MOVE = Messages.getString("PosMessage.412"); //$NON-NLS-1$
	public static final String ARTICKEL_UPDATE = Messages.getString("PosMessage.413"); //$NON-NLS-1$
	public static final String ARTICKEL_INSTANT_CANCEL = Messages.getString("PosMessage.414"); //$NON-NLS-1$
	
	
	public static final String SALES_DATE = Messages.getString("SalesReport.0"); //$NON-NLS-1$
	public static final String SALES_REVENUE = Messages.getString("SalesReport.1"); //$NON-NLS-1$
	public static final String SALES_TOTAL_SUM = Messages.getString("SalesReport.2"); //$NON-NLS-1$
	public static final String SALES_NET_TOTAL = Messages.getString("SalesReport.3"); //$NON-NLS-1$
	public static final String SALES_NET = Messages.getString("SalesReport.4"); //$NON-NLS-1$
	public static final String SALES_VAT = Messages.getString("SalesReport.5"); //$NON-NLS-1$
	public static final String SALES_TOTAL_RETURN_COUNT = Messages.getString("SalesReport.6"); //$NON-NLS-1$
	public static final String SALES_TOTAL_RETURN_AMOUNT = Messages.getString("SalesReport.7"); //$NON-NLS-1$
	public static final String SALES_TOTAL_RETURN_VAT = Messages.getString("SalesReport.8"); //$NON-NLS-1$
	public static final String SALES_TOTAL_CANCELED = Messages.getString("SalesReport.9"); //$NON-NLS-1$
	public static final String SALES_TOTAL_CANCELED_AMOUNT = Messages.getString("SalesReport.10"); //$NON-NLS-1$
	public static final String SALES_TOTAL_CANCEL_VAT = Messages.getString("SalesReport.11"); //$NON-NLS-1$
	public static final String SALES_TOTAL_BILLS = Messages.getString("SalesReport.12"); //$NON-NLS-1$
	public static final String SALES_TOTAL_SOLD_PRODUCT = Messages.getString("SalesReport.13"); //$NON-NLS-1$
	public static final String SALES_CASH_PAYMENT = Messages.getString("SalesReport.14"); //$NON-NLS-1$
	public static final String SALES_VAT_TOTAL = Messages.getString("SalesReport.15"); //$NON-NLS-1$
	public static final String SALES_COUNT = Messages.getString("SalesReport.16"); //$NON-NLS-1$
	public static final String SALES_CARD_PAYMENT = Messages.getString("SalesReport.17"); //$NON-NLS-1$
	public static final String SALES_GOODSCHEINCARD_PAYMENT = Messages.getString("SalesReport.24"); //$NON-NLS-1$
	public static final String SALES_DISCOUNT = Messages.getString("SalesReport.18"); //$NON-NLS-1$
	public static final String SALES_CASH_CASDRAWER = Messages.getString("SalesReport.19"); //$NON-NLS-1$
	public static final String SALES_SUM_TOTAL = Messages.getString("SalesReport.20"); //$NON-NLS-1$
	public static final String SALES_GOODS_ACOUNTING = Messages.getString("SalesReport.21"); //$NON-NLS-1$ 
	public static final String SALES_GOODS = Messages.getString("SalesReport.22"); //$NON-NLS-1$
	public static final String SALES_TOTAL = Messages.getString("SalesReport.23"); //$NON-NLS-1$	
	public static final String SALES_COUPON = Messages.getString("SalesReport.24"); //$NON-NLS-1$	
	public static final String SALES_COUPON_REDEEMED = Messages.getString("SalesReport.25"); //$NON-NLS-1$	
	public static final String SALES_CASH_TIP = Messages.getString("SalesReport.26"); //$NON-NLS-1$	
	public static final String SALES_OTHER_TIP = Messages.getString("SalesReport.27"); //$NON-NLS-1$	
	public static final String SALES_RABATT_19 = Messages.getString("SalesReport.28"); //$NON-NLS-1$	
	public static final String SALES_RABATT_7 = Messages.getString("SalesReport.29"); //$NON-NLS-1$	
	
	public static final String BACK_CONFIGURATION =Messages.getString("BackOffice.1");
	public static final String BACK_USER =Messages.getString("BackOffice.2");
	public static final String BACK_PRODUCT_EXPORT =Messages.getString("BackOffice.3");
	public static final String BACK_PRODUCT_IMPORT =Messages.getString("BackOffice.4");
	public static final String BACK_CONFIG_TEXT =Messages.getString("BackOffice.5");
	public static final String BACK_BILLS =Messages.getString("BackOffice.6");
	public static final String BACK_CATEGORIES =Messages.getString("BackOffice.7");
	public static final String BACK_GROUPS =Messages.getString("BackOffice.8");
	public static final String BACK_PRODUCT =Messages.getString("BackOffice.9");
	public static final String BACK_EXTRA_GROUPS =Messages.getString("BackOffice.10");
	public static final String BACK_CUSTOMERS =Messages.getString("BackOffice.11");
	public static final String BACK_ABS_ARCHIV =Messages.getString("BackOffice.12");
	public static final String BACK_ZAHLUNGABS =Messages.getString("BackOffice.13");
	public static final String BACK_ABSRESET =Messages.getString("BackOffice.14");
	public static final String BACK_AUSWAHL =Messages.getString("BackOffice.15");
	public static final String BACK_RABATTE =Messages.getString("BackOffice.16");
	public static final String BACK_STEUERN =Messages.getString("BackOffice.17");
	public static final String BACK_INVENTUR =Messages.getString("BackOffice.18");
	public static final String BACK_GUTSCHEIN =Messages.getString("BackOffice.19");
	public static final String BACK_REPORT =Messages.getString("BackOffice.20");
	public static final String BACK_HELP =Messages.getString("BackOffice.21");
	public static final String BACK_CLOSE =Messages.getString("BackOffice.22");
	public static final String VERKAUFSSTATISTIK =Messages.getString("BackOffice.23");
	
	public static final String Geschaeft =Messages.getString("Geschaeft.1");
	public static final String Geschaeft_name =Messages.getString("Geschaeft.2");
	public static final String Anschrift =Messages.getString("Geschaeft.3");
	public static final String Zusatz =Messages.getString("Geschaeft.4");
	public static final String Stadt =Messages.getString("Geschaeft.5");
	public static final String PLZ =Messages.getString("Geschaeft.6");
	public static final String Telefon =Messages.getString("Geschaeft.7");
	public static final String Waehrung =Messages.getString("Geschaeft.8");
	public static final String Waehrungssymbol =Messages.getString("Geschaeft.9");
	public static final String Bon_Fusszeile1 =Messages.getString("Geschaeft.10");
	public static final String Bon_Fusszeile2 =Messages.getString("Geschaeft.11");
	public static final String Steuer_Nr =Messages.getString("Geschaeft.12");
	public static final String Kunden_Display_Text1 =Messages.getString("Geschaeft.13");
	public static final String Kunden_Display_Text2 =Messages.getString("Geschaeft.14");
	public static final String Grußtext =Messages.getString("Geschaeft.15");
	 
	public static final String Terminal= Messages.getString("Terminal.1");
	public static final String Terminal_Number= Messages.getString("Terminal.2");
	public static final String Tages_Abschluss_id= Messages.getString("Terminal.3");
	public static final String Monatabschluss_id= Messages.getString("Terminal.4");
	public static final String Startpunkt_Kundennr= Messages.getString("Terminal.5");
	public static final String Maximale_Bestellung= Messages.getString("Terminal.6");
	public static final String Schublade_File= Messages.getString("Terminal.7");
	public static final String Schublade_Com= Messages.getString("Terminal.8");
	public static final String Schlußel_COM= Messages.getString("Terminal.9");
	public static final String Mehrer_ausdrucke= Messages.getString("Terminal.10");
	public static final String Waage_COM_PORT= Messages.getString("Terminal.11");
	public static final String Kunden_Display_COM_PORT= Messages.getString("Terminal.12");
	public static final String Aus_Zahlung1= Messages.getString("Terminal.13");
	public static final String Aus_Zahlung2= Messages.getString("Terminal.14");
	public static final String Aus_Zahlung3= Messages.getString("Terminal.15");
	public static final String Start_Datum= Messages.getString("Terminal.16");
	public static final String Default_Schrift= Messages.getString("Terminal.17");
	public static final String TOUCH_SCREEN_EINSTELLUNGEN= Messages.getString("Terminal.18");
	public static final String Buttonhoehe= Messages.getString("Terminal.19");
	public static final String Kategorie_Buttonhoehe= Messages.getString("Terminal.20");
	public static final String Kategorie_ButtonBreit= Messages.getString("Terminal.21");
	public static final String Schriftgroesse= Messages.getString("Terminal.22");
	public static final String Hoehe_des_Artikelbuttons= Messages.getString("Terminal.23");
	public static final String Breite_des_Artikelbuttons= Messages.getString("Terminal.24");
	public static final String Rot_Artikel= Messages.getString("Terminal.25");
	public static final String Gruene_Artikel= Messages.getString("Terminal.26");
	public static final String Blaue_Artikel= Messages.getString("Terminal.27");
	public static final String wieder_starten= Messages.getString("Terminal.28");
	public static final String Automatische_Abmeldung= Messages.getString("Terminal.29");
	public static final String ISDN_Dienstleistung= Messages.getString("Terminal.30");
	public static final String Kunden_Display= Messages.getString("Terminal.31");
	public static final String Kassenschublade= Messages.getString("Terminal.32");
	public static final String Kassenschublade_mit_Drucker= Messages.getString("Terminal.33");
	public static final String Lieferungsdruck_an_Kueche= Messages.getString("Terminal.34");
	public static final String Passwortlaenge= Messages.getString("Terminal.35");
	public static final String Auto_Logout_Time= Messages.getString("Terminal.36");
	public static final String Kurzere_Tagesbericht= Messages.getString("Terminal.37");
	public static final String Feindruck= Messages.getString("Terminal.38");
	public static final String Liefezeit= Messages.getString("Terminal.39");
	public static final String Kurze_Rechnung= Messages.getString("Terminal.40");
	public static final String Tab_Druck= Messages.getString("Terminal.41");
	public static final String Nur_Barzahlung= Messages.getString("Terminal.42");
	public static final String Mehrere_Ausdrucke= Messages.getString("Terminal.43");
	public static final String EUR_display_Verstecken= Messages.getString("Terminal.44");
	public static final String Comma_zahlen= Messages.getString("Terminal.45");
	public static final String Ticket_o_Id= Messages.getString("Terminal.46");
	public static final String Rechnung_nur_mit_Datum= Messages.getString("Terminal.47");
	public static final String Schublade_verstecken= Messages.getString("Terminal.48");
	public static final String Beider_Eingabe= Messages.getString("Terminal.49");
	
	
	public static final String Daten_Drucker= Messages.getString("TerminalConfigurationView.15");
	public static final String Bon_Drucker= Messages.getString("TerminalConfigurationView.16");
	public static final String A4_Drucker= Messages.getString("TerminalConfigurationView.17");
	public static final String Sonstige_Drucker= Messages.getString("TerminalConfigurationView.18");
	public static final String Bon= Messages.getString("TerminalConfigurationView.19");
	
	public static final String Daten_Loeschen= Messages.getString("DeleteAllView.1");
	public static final String Rechnung_Loeschen= Messages.getString("DeleteAllView.2");
	public static final String Menue= Messages.getString("DeleteAllView.3");
	public static final String Rechnung= Messages.getString("DeleteAllView.4");
	public static final String Steuer= Messages.getString("DeleteAllView.5");
	public static final String Sales_Report= Messages.getString("DeleteAllView.6");
	public static final String Alles_auswaehlen= Messages.getString("DeleteAllView.7");
	public static final String Grund_für_Loeschvorgang= Messages.getString("DeleteAllView.8");
	public static final String LIZENZ= Messages.getString("DeleteAllView.9");
	public static final String Invetuar= Messages.getString("DeleteAllView.10");
	
	public static final String Vorname= Messages.getString("User.2");
	public static final String Nachname= Messages.getString("User.3");
	public static final String Passcode= Messages.getString("User.4");
	public static final String Bestaetigen_Key= Messages.getString("User.5");
	public static final String Schluessel= Messages.getString("User.6");
	public static final String Kostet_pro_Stunde= Messages.getString("User.7");
	public static final String Benutzertyp= Messages.getString("User.8");
	public static final String Bild= Messages.getString("User.9");
	public static final String entfernen= Messages.getString("User.10");
	public static final String Verfuegbar_= Messages.getString("User.11");
	
	public static final String Abschliessen= Messages.getString("Haupt.1");
	public static final String Rechnung_schliessen= Messages.getString("Haupt.2");
	public static final String Art_Sonstiges_Text= Messages.getString("Haupt.3");
	public static final String wieder_oeffnen= Messages.getString("Haupt.4");
	public static final String Rechnung_loeschen= Messages.getString("Haupt.5");
	public static final String Alte_Rechnungen= Messages.getString("Haupt.6");
	public static final String Kassenbuch= Messages.getString("Haupt.7");
	public static final String Sichtbar= Messages.getString("Haupt.8");
	public static final String Speichern= Messages.getString("Haupt.9");
	
	public static final String Sofort_zahlen= Messages.getString("Bestellung.1");
	public static final String Spaeter_zahlen= Messages.getString("Bestellung.2");
	public static final String Diverse= Messages.getString("Bestellung.3");
	public static final String Artikel_hinzufuegen= Messages.getString("Bestellung.4");
	public static final String Rechnungsvorschau= Messages.getString("Bestellung.5");
	public static final String Artikel_loeschen= Messages.getString("Bestellung.6");
	public static final String Rabatt_Direkt= Messages.getString("Bestellung.7");
	public static final String Sons_Waage_btnName= Messages.getString("Bestellung.8");
	
	public static final String Vorschau= Messages.getString("Selection.1");
	public static final String Rabatt= Messages.getString("Selection.2");
	
	public static final String Schublade_Oeffnen= Messages.getString("Selection.3");
	public static final String Art_suchen= Messages.getString("Selection.4");
	public static final String Saldo= Messages.getString("Selection.5");
	public static final String Receipt_Mit_QR= Messages.getString("Selection.6");
	public static final String Rabatt_19= Messages.getString("Selection.7");
	public static final String Rabatt_7= Messages.getString("Selection.8");
	public static final String Inventur_alert= Messages.getString("Selection.9");
	public static final String Karte= Messages.getString("Selection.10");
	public static final String Duplikat_Rechnug= Messages.getString("Selection.11");
	public static final String Warengroup_Abs= Messages.getString("Selection.12");
	public static final String Zuruck_Dialog= Messages.getString("Selection.13");
	public static final String Art_Preis_verstecken= Messages.getString("Selection.14");
	public static final String Art_Id_verstecken= Messages.getString("Selection.15");
	public static final String Tagesabs_mit_Zahlung= Messages.getString("Selection.16");
	public static final String Finazpruefung= Messages.getString("Selection.17");
	public static final String Kunden_Nr_Price_list= Messages.getString("Selection.18");
	public static final String Produkt_Add= Messages.getString("Selection.19");
	public static final String Storno_Kellner= Messages.getString("Selection.20");	
	public static final String Druck_Display= Messages.getString("Selection.21");
	public static final String Druck_Footer_Nachricht= Messages.getString("Selection.22");
	public static final String Online_Zahlung= Messages.getString("Selection.23");
	public static final String Taschenrechner= Messages.getString("Selection.24");
	public static final String Bon_Roll= Messages.getString("Selection.25");
	public static final String Trinkgeld= Messages.getString("Selection.26");
	public static final String Normal_Auswal_Enable= Messages.getString("Selection.27");
	public static final String Waehlen= Messages.getString("Selection.28");
	public static final String ABBRECHEN= Messages.getString("Selection.29");
	public static final String MitarbeiterAbschluss= Messages.getString("Selection.30");
	public static final String Bestellen= Messages.getString("Selection.31");
	public static final String Kunden= Messages.getString("Selection.32");
	public static final String Kein_karte_Bestaetigung= Messages.getString("Selection.33");
	public static final String Speisegruppe= Messages.getString("Explorer.1");
	public static final String Bestand= Messages.getString("Explorer.2");
	public static final String Inhalt= Messages.getString("Explorer.3");
	public static final String Liferant= Messages.getString("Explorer.4");
	public static final String Einkaufspreis= Messages.getString("Explorer.5");
	public static final String Druck_Alle= Messages.getString("Explorer.6");
	public static final String Liefer_Datum= Messages.getString("Explorer.7");
	public static final String Zahlungsstatus= Messages.getString("Explorer.8");
	public static final String Druck_Zeit= Messages.getString("Explorer.9");
	public static final String Tisch= Messages.getString("Explorer.10");
	public static final String Bezahlt= Messages.getString("Explorer.11");
	public static final String RABATT= Messages.getString("LABEL_DISCOUNT_RATE");	
	public static final String Beschreibung= Messages.getString("Explorer.12");
	public static final String Bemerkung= Messages.getString("Explorer.13");
	public static final String Generieren= Messages.getString("Explorer.14");
	public static final String Gewicht= Messages.getString("Explorer.15");
	public static final String Bilder_anzeigen= Messages.getString("Explorer.16");
	public static final String DUPLIKAT= Messages.getString("Explorer.17");
	public static final String KOPIEREN= Messages.getString("Explorer.18");
	public static final String Auswahl_Hinzufugen= Messages.getString("Explorer.19");
	public static final String HINZUFUGEN= Messages.getString("Explorer.20");
	public static final String Neue_Menuezutat= Messages.getString("Explorer.21");
	public static final String Menuezutat_bearbeiten= Messages.getString("Explorer.22");
	public static final String Strasse= Messages.getString("Explorer.23");
	public static final String Kunden_Nr= Messages.getString("Explorer.24");
	public static final String Firma= Messages.getString("Explorer.25");
	public static final String Firma_Name= Messages.getString("Explorer.26");
	public static final String Salutation= Messages.getString("Explorer.27");
	public static final String Verkauft= Messages.getString("Explorer.28");
	public static final String Beschaedigt= Messages.getString("Explorer.29");
	public static final String Artikelmenge_Hinzufügen= Messages.getString("Explorer.30");
	public static final String Gueltig_bis= Messages.getString("Explorer.31");
	public static final String Unendlich= Messages.getString("Explorer.32");
	public static final String Erstellt= Messages.getString("Explorer.33");
	public static final String Druck_Report= Messages.getString("Explorer.34");
	public static final String Alles_anzeigen= Messages.getString("Explorer.35");
	public static final String Abgeschlossen= Messages.getString("Explorer.36");
	public static final String Endlich_Datum= Messages.getString("Explorer.37");
	public static final String Anz= Messages.getString("Explorer.38");
	public static final String Artikel= Messages.getString("Explorer.39");
	
	
	public static final String Gutscheinname= Messages.getString("Gutschein.1");
	public static final String Ablaufdatum= Messages.getString("Gutschein.2");
	public static final String Gutscheintyp= Messages.getString("Gutschein.3");
	public static final String Prozente_Artikel= Messages.getString("Gutschein.4");
	public static final String Gutscheinwert= Messages.getString("Gutschein.5");
	public static final String ungueltig= Messages.getString("Gutschein.6");
	public static final String Laeuft_nie_aus= Messages.getString("Gutschein.7");
	public static final String Freiwilliges= Messages.getString("Gutschein.8");
	public static final String Hinzufügen_Gutschein= Messages.getString("Gutschein.9");
	public static final String Gutschein_Bearbeiten= Messages.getString("Gutschein.10");
	public static final String Gutschein_Nummer= Messages.getString("Gutschein.11");
	public static final String Gutschein_Note= Messages.getString("Gutschein.12");
	public static final String Gutschein_preis= Messages.getString("Gutschein.13");
	public static final String Zahl_Art= Messages.getString("Gutschein.14");
	
	
	public static final String nicht_gefunden= Messages.getString("MsgDialog.1");
	public static final String Nicht_verfuegbar = Messages.getString("MsgDialog.2");
	public static final String Beschaedigt_produckte = Messages.getString("MsgDialog.3");
	public static final String Verfuegbar_produckte = Messages.getString("MsgDialog.4");
	public static final String name_suchen = Messages.getString("MsgDialog.5");
	public static final String Barcode_suchen = Messages.getString("MsgDialog.6");
	public static final String suchen = Messages.getString("MsgDialog.7");
	
	public static final String zu_hoch = Messages.getString("Bestellung_.1");
	public static final String Bestellung_aus = Messages.getString("Bestellung_.2");
	public static final String Geben_Oder_Scannen = Messages.getString("Bestellung_.3");
	public static final String Geloechte_Rechnungen = Messages.getString("Bestellung_.4");
	public static final String BAR = Messages.getString("Bestellung_.5");
	public static final String Bar_Druck = Messages.getString("Bestellung_.6");
	public static final String Uberweisen = Messages.getString("Bestellung_.7");
	public static final String Zuruck = Messages.getString("Bestellung_.8");
	public static final String SCHUBLADE_OFFNEN = Messages.getString("Bestellung_.9");
	public static final String Split_ZAHLEN = Messages.getString("Bestellung_.10");
	public static final String A4_Rechnung = Messages.getString("Bestellung_.11");
	public static final String Zurueck_Geld = Messages.getString("Bestellung_.12");
	public static final String SCHLIESSEN = Messages.getString("Bestellung_.13");
	public static final String WARNUNG = Messages.getString("Bestellung_.14");
	public static final String Kartenzahlung = Messages.getString("Bestellung_.15");
	public static final String Gutschein_Verkaufen = Messages.getString("Bestellung_.16");
	public static final String Bestellungen = Messages.getString("Bestellung_.17");
	
	public static final String Waehlen_rabatt = Messages.getString("Bestellung_.18");
	public static final String Rab_entfernen = Messages.getString("Bestellung_.19");
	public static final String Rabatt_entfernt = Messages.getString("Bestellung_.20");
	public static final String Kein_Rabatt_Gefunden = Messages.getString("Bestellung_.21");
	public static final String Rabatt_name = Messages.getString("Bestellung_.22");
	public static final String Rabatt_nr = Messages.getString("Bestellung_.23");
	public static final String RabattTyp = Messages.getString("Bestellung_.24");
	public static final String Rabatt_Prcnt = Messages.getString("Bestellung_.25");
	public static final String Rabatt_summe = Messages.getString("Bestellung_.26");
	public static final String Ticket_bereits_Rabatt = Messages.getString("Bestellung_.27");
	public static final String wahlen_einen_Gutschein = Messages.getString("Bestellung_.28");
	public static final String Coupn_type1 = Messages.getString("Bestellung_.29");
	public static final String Coupn_type2 = Messages.getString("Bestellung_.30");
	public static final String Coupn_type3 = Messages.getString("Bestellung_.31");
	public static final String Coupn_type4 = Messages.getString("Bestellung_.32");
	public static final String Coupn_type5 = Messages.getString("Bestellung_.33");
	public static final String Coupn_type6 = Messages.getString("Bestellung_.34");
	public static final String Coupn_type7 = Messages.getString("Bestellung_.35");
	public static final String Preis_EUR = Messages.getString("Bestellung_.36");
	public static final String Rabatt_Preis = Messages.getString("Bestellung_.37");
	public static final String Aktuelle_Rabatte = Messages.getString("Bestellung_.38");
	public static final String Dir_Rbt_entf = Messages.getString("Bestellung_.39");
	public static final String Guts_entf = Messages.getString("Bestellung_.40");
	public static final String Waehlen_dirRbt = Messages.getString("Bestellung_.41");
	public static final String Wertbon_entf = Messages.getString("Bestellung_.42");
	public static final String Restbetrag = Messages.getString("Bestellung_.43");
	public static final String Abgeschlossen_dirRbt = Messages.getString("Bestellung_.44");
	public static final String Offnen_dirRbt = Messages.getString("Bestellung_.45");
	public static final String Fertig = Messages.getString("Bestellung_.46");
	public static final String Wertbon = Messages.getString("Bestellung_.47");
	public static final String Aenderungen_vornehmen = Messages.getString("Bestellung_.48");
	
	public static final String Achtung = Messages.getString("Bestellung_.49");
	public static final String Menue_ueberschreiben = Messages.getString("Bestellung_.50");
	public static final String Tages_Abschluss = Messages.getString("Bestellung_.51");
	public static final String X_ABSCHLUSS = Messages.getString("Bestellung_.52");
	public static final String Z_ABSCHLUSS = Messages.getString("Bestellung_.53");
	public static final String Z_ABSCHLAG = Messages.getString("Bestellung_.54");
	public static final String X_ABSCHLAG = Messages.getString("Bestellung_.55");
	public static final String Wollen_Sie_Drucken = Messages.getString("Bestellung_.56");
	public static final String Tages_Abschluss_fur  = Messages.getString("Bestellung_.57");
	public static final String schon_ausgedruckt = Messages.getString("Bestellung_.58");
	public static final String AKTUALISIEREN = Messages.getString("Bestellung_.59");
	public static final String Sind_Sie_sicher = Messages.getString("Bestellung_.60");
	public static final String T_Abschulss = Messages.getString("Bestellung_.61");
	public static final String Monatabschluss = Messages.getString("Bestellung_.62");
	public static final String Monat = Messages.getString("Bestellung_.63");
	public static final String Jahr = Messages.getString("Bestellung_.64");
	public static final String JAHRES_ABS = Messages.getString("Bestellung_.65");
	public static final String Z_ABSCHLUSS_Monat = Messages.getString("Bestellung_.66");
	public static final String X_ABSCHLAG_monat = Messages.getString("Bestellung_.67");
	public static final String MITARBEITER = Messages.getString("Bestellung_.68");
	public static final String SUMME = Messages.getString("Bestellung_.69");
	public static final String DATUM = Messages.getString("Bestellung_.70");
	
	
	public static final String Tax_drinks = Messages.getString("Tax.1");
	public static final String Tax_food = Messages.getString("Tax.2");
	
	
	
	}
